addTest("../Parameters/cellResolution001.xml","cellResolution001","Test ttp:cellResolution attribute","Parameter Test");
addTest("../Parameters/clockMode001.xml","clockMode001","Test ttp:clockMode attribute","Parameter Test");
addTest("../Parameters/clockMode002.xml","clockMode002","Test ttp:clockMode attribute","Parameter Test");
addTest("../Parameters/clockMode003.xml","clockMode003","Test ttp:clockMode attribute","Parameter Test");
addTest("../Parameters/frameRate001.xml","frameRate001","Test ttp:frameRate attribute","Parameter Test");
addTest("../Parameters/frameRate002.xml","frameRate002","Test ttp:frameRate attribute","Parameter Test");
addTest("../Parameters/frameRateMultiplier001.xml","frameRateMultiplier001","Test ttp:frameRateMultiplier attribute","Parameter Test");
addTest("../Parameters/markerMode001.xml","markerMode001","Test ttp:markerMode attribute","Parameter Test");
addTest("../Parameters/markerMode002.xml","markerMode002","Test ttp:markerMode attribute","Parameter Test");
addTest("../Parameters/smpteMode001.xml","smpteMode001","Test ttp:smpteMode attribute","Parameter Test");
addTest("../Parameters/smpteMode002.xml","smpteMode002","Test ttp:smpteMode attribute","Parameter Test");
addTest("../Parameters/subFrameRate001.xml","subFrameRate001","Test ttp:subFrameRate attribute","Parameter Test");
addTest("../Parameters/tickRate001.xml","tickRate001","Test ttp:tickRate attribute","Parameter Test");
addTest("../Parameters/timeBase001.xml","timeBase001","Test ttp:timeBase attribute","Parameter Test");
addTest("../Parameters/timeBase002.xml","timeBase002","Test ttp:timeBase attribute","Parameter Test");
addTest("../Parameters/timeBase003.xml","timeBase003","Test ttp:timeBase attribute","Parameter Test");
addTest("../Content/Br001.xml","Br001","Test the br element.","Content Test");
addTest("../Content/Paragraph001.xml","Paragraph001","Test the p element with no styling attribute.","Content Test");
addTest("../Content/Paragraph002.xml","Paragraph002","Test the p element with no timing attributes (nothing is displayed).","Content Test");
addTest("../Content/Paragraph003.xml","Paragraph003","Test the p element with styling and timing attributes.","Content Test");
addTest("../Content/Paragraph004.xml","Paragraph004","Test the p element with xml:space default.","Content Test");
addTest("../Content/Paragraph005.xml","Paragraph005","Test the p element with xml:space preserve.","Content Test");
addTest("../Content/Span001.xml","Span001","Test the span element with no attributes.","Content Test");
addTest("../Content/Span002.xml","Span002","Test the span element with a styling attribute.","Content Test");
addTest("../Content/Span003.xml","Span003","Test nested span elements.","Content Test");
addTest("../Content/Span004.xml","Span004","Test nested span elements.","Content Test");
addTest("../Content/Span005.xml","Span005","Test the br element inside a span element.","Content Test");
addTest("../Content/div001.xml","div001","Test nested div elements.","Content Test");
addTest("../Content/div002.xml","div002","Test multiple div elements in the body.","Content Test");
addTest("../Content/div003.xml","div003","Test multiple div elements in the body with the xml:lang attribute.","Content Test");
addTest("../Content/foreign001.xml","foreign001","Test the non-TT namespaces.","Content Test");
addTest("../Content/tt001.xml","tt001","Test the tt element without an xml:space attribute.","Content Test");
addTest("../Content/tt002.xml","tt002","Test the tt element with xml:space preserve.","Content Test");
addTest("../Content/tt003.xml","tt003","Test the tt element with xml:space default.","Content Test");
addTest("../Styling/BackgroundColor001.xml","BackgroundColor001","Test tts:backgroundColor attribute using a named color expression in a div.","Styling Test");
addTest("../Styling/BackgroundColor002.xml","BackgroundColor002","Test tts:backgroundColor attribute using a hash (#rrggbb) color expression in a div.","Styling Test");
addTest("../Styling/BackgroundColor003.xml","BackgroundColor003","Test tts:backgroundColor attribute using a hash (#rrggbbaa) color expression with opacity on the body.","Styling Test");
addTest("../Styling/BackgroundColor004.xml","BackgroundColor004","Test tts:backgroundColor attribute using a rgb() color function on the body.","Styling Test");
addTest("../Styling/BackgroundColor005.xml","BackgroundColor005","Test tts:backgroundColor attribute using a rgba() color function using a span.","Styling Test");
addTest("../Styling/BackgroundColor006.xml","BackgroundColor006","Test tts:backgroundColor attribute using a transparent value.","Styling Test");
addTest("../Styling/BackgroundColor007.xml","BackgroundColor007","Test tts:backgroundColor using a named color expression on the div element.","Styling Test");
addTest("../Styling/BackgroundColor008.xml","BackgroundColor008","Test tts:backgroundColor style using a named color expression in style.","Styling Test");
addTest("../Styling/BackgroundColor009.xml","BackgroundColor009","Test tts:backgroundColor using a named color expression on the body.","Styling Test");
addTest("../Styling/Color001.xml","Color001","Test tts:color attribute using a named color expression.","Styling Test");
addTest("../Styling/Color002.xml","Color002","Test tts:color attribute using a hash (#rrggbb) color expression.","Styling Test");
addTest("../Styling/Color003.xml","Color003","Test tts:color attribute using a hash (#rrggbbaa) color expression with opacity.","Styling Test");
addTest("../Styling/Color004.xml","Color004","Test tts:color attribute using a rgb() color function.","Styling Test");
addTest("../Styling/Color005.xml","Color005","Test tts:color attribute using a rgba() color function.","Styling Test");
addTest("../Styling/Color006.xml","Color006","Test tts:color attribute using a inherit value.","Styling Test");
addTest("../Styling/Color007.xml","Color007","Test tts:color attribute using a transparent value.","Styling Test");
addTest("../Styling/Color008.xml","Color008","Test tts:color attribute with span elements.","Styling Test");
addTest("../Styling/Color009.xml","Color009","Test tts:color style using a named color expression.","Styling Test");
addTest("../Styling/LineHeight001.xml","LineHeight001","Test tts:lineHeight attribute using the normal value.","Styling Test");
addTest("../Styling/LineHeight002.xml","LineHeight002","Test tts:lineHeight attribute using the normal value in a span.","Styling Test");
addTest("../Styling/LineHeight003.xml","LineHeight003","Test tts:lineHeight attribute using a length value.","Styling Test");
addTest("../Styling/LineHeight004.xml","LineHeight004","Test tts:lineHeight attribute using the inherit value.","Styling Test");
addTest("../Styling/Padding001.xml","Padding001","Test tts:padding attribute with one value.","Styling Test");
addTest("../Styling/Padding002.xml","Padding002","Test tts:padding attribute with two values.","Styling Test");
addTest("../Styling/Padding003.xml","Padding003","Test tts:padding attribute with three values.","Styling Test");
addTest("../Styling/Padding004.xml","Padding004","Test tts:padding attribute with four values.","Styling Test");
addTest("../Styling/Padding005.xml","Padding005","Test tts:padding attribute with an inherited value.","Styling Test");
addTest("../Styling/Style001.xml","Style001","Test style attributes in the style element.","Styling Test");
addTest("../Styling/Styling001.xml","Styling001","Test two different styles in the style element.","Styling Test");
addTest("../Styling/TextAlign001.xml","TextAlign001","Test tts:textAlign attribute with the right value in a paragraph.","Styling Test");
addTest("../Styling/TextAlign002.xml","TextAlign002","Test tts:textAlign attribute with the left value in a span.","Styling Test");
addTest("../Styling/TextAlign003.xml","TextAlign003","Test tts:textAlign attribute with the center value in style.","Styling Test");
addTest("../Styling/TextAlign004.xml","TextAlign004","Test tts:textAlign attribute with the right value on the body.","Styling Test");
addTest("../Styling/TextAlign005.xml","TextAlign005","Test tts:textAlign attribute with the left value on div.","Styling Test");
addTest("../Styling/TextAlign006.xml","TextAlign006","Test tts:textAlign attribute with the center value on a span.","Styling Test");
addTest("../Styling/TextAlign007.xml","TextAlign007","Test tts:textAlign attribute with the start value.","Styling Test");
addTest("../Styling/TextAlign008.xml","TextAlign008","Test tts:textAlign attribute with the end value.","Styling Test");
addTest("../Styling/TextAlign009.xml","TextAlign009","Test tts:textAlign attribute with the inherit value.","Styling Test");
addTest("../Styling/TextDecoration001.xml","TextDecoration001","Test tts:textDecoration attribute using the none value.","Styling Test");
addTest("../Styling/TextDecoration002.xml","TextDecoration002","Test tts:textDecoration attribute using the underline value in a span.","Styling Test");
addTest("../Styling/TextDecoration003.xml","TextDecoration003","Test tts:textDecoration attribute using the none value in a span.","Styling Test");
addTest("../Styling/TextDecoration004.xml","TextDecoration004","Test tts:textDecoration attribute using the underline value in style.","Styling Test");
addTest("../Styling/TextDecoration005.xml","TextDecoration005","Test tts:textDecoration attribute with the underline value in a div.","Styling Test");
addTest("../Styling/TextDecoration006.xml","TextDecoration006","Test tts:textDecoration attribute with the underline value in the body.","Styling Test");
addTest("../Styling/TextDecoration007.xml","TextDecoration007","Test tts:textDecoration attribute with the noUnderline value.","Styling Test");
addTest("../Styling/TextDecoration008.xml","TextDecoration008","Test tts:textDecoration attribute with the lineThrough value.","Styling Test");
addTest("../Styling/TextDecoration009.xml","TextDecoration009","Test tts:textDecoration attribute with the noLineThrough value.","Styling Test");
addTest("../Styling/TextDecoration010.xml","TextDecoration010","Test tts:textDecoration attribute with the overline value.","Styling Test");
addTest("../Styling/TextDecoration011.xml","TextDecoration011","Test tts:textDecoration attribute with the noOverline value.","Styling Test");
addTest("../Styling/TextDecoration012.xml","TextDecoration012","Test tts:textDecoration attribute with the inherit value.","Styling Test");
addTest("../Styling/TextOutline001.xml","TextOutline001","Test tts:textOutline attribute using the none value.","Styling Test");
addTest("../Styling/TextOutline002.xml","TextOutline002","Test tts:textOutline attribute using a value for outline thickness.","Styling Test");
addTest("../Styling/TextOutline003.xml","TextOutline003","Test tts:textOutline attribute using values for outline thickness and blur radius.","Styling Test");
addTest("../Styling/TextOutline004.xml","TextOutline004","Test tts:textOutline attribute using values for color and outline thickness.","Styling Test");
addTest("../Styling/TextOutline005.xml","TextOutline005","Test tts:textOutline attribute using values for color, outline thickness and blur radius.","Styling Test");
addTest("../Styling/TextOutline006.xml","TextOutline006","Test tts:textOutline attribute using the inherit value.","Styling Test");
addTest("../Styling/Visibility001.xml","Visibility001","Test tts:visibility attribute using the visible value.","Styling Test");
addTest("../Styling/Visibility002.xml","Visibility002","Test tts:visibility attribute using the visible value.","Styling Test");
addTest("../Styling/Visibility003.xml","Visibility003","Test tts:visibility attribute using the hidden value.","Styling Test");
addTest("../Styling/Visibility004.xml","Visibility004","Test tts:visibility attribute using the inherit value.","Styling Test");
addTest("../Styling/direction001.xml","direction001","Test tts:direction attribute with the ltr value in a paragraph.","Styling Test");
addTest("../Styling/direction002.xml","direction002","Test tts:direction attribute with the ltr value in the style element.","Styling Test");
addTest("../Styling/direction003.xml","direction003","Test tts:direction attribute with the rtl value in the style element.","Styling Test");
addTest("../Styling/direction004.xml","direction004","Test tts:direction attribute with the rtl value in a span.","Styling Test");
addTest("../Styling/direction005.xml","direction005","Test tts:direction attribute with the rtl value in a paragraph.","Styling Test");
addTest("../Styling/direction006.xml","direction006","Test tts:direction attribute with the ltr value in a span.","Styling Test");
addTest("../Styling/direction007.xml","direction007","Test tts:direction attribute with the inherit value in a span.","Styling Test");
addTest("../Styling/display001.xml","display001","Test tts:display attribute with the auto value in the style element.","Styling Test");
addTest("../Styling/display002.xml","display002","Test tts:display attribute with the none value in a paragraph.","Styling Test");
addTest("../Styling/display003.xml","display003","Test tts:display attribute with the inherit value in a span.","Styling Test");
addTest("../Styling/display004.xml","display004","Test tts:display attribute with the none value in the style element.","Styling Test");
addTest("../Styling/displayAlign001.xml","displayAlign001","Test tts:displayAlign attribute with the before value in the style element.","Styling Test");
addTest("../Styling/displayAlign002.xml","displayAlign002","Test tts:displayAlign attribute with the after value in the style element.","Styling Test");
addTest("../Styling/displayAlign003.xml","displayAlign003","Test tts:displayAlign attribute with the center value in the style element.","Styling Test");
addTest("../Styling/displayAlign004.xml","displayAlign004","Test tts:displayAlign attribute with an inherit value.","Styling Test");
addTest("../Styling/extent001.xml","extent001","Test tts:extent attribute with the auto value in the style element.","Styling Test");
addTest("../Styling/extent002.xml","extent002","Test tts:extent attribute with two length values in the style element.","Styling Test");
addTest("../Styling/extent003.xml","extent003","Test tts:extent attribute with an inherited value.","Styling Test");
addTest("../Timing/BeginDur001.xml","BeginDur001","Test the begin and dur attributes on p elements.","Timing Test");
addTest("../Timing/BeginEnd001.xml","BeginEnd001","Test the begin and end attributes on p elements.","Timing Test");
addTest("../Timing/BeginEnd002.xml","BeginEnd002","Test the begin attribute with no end or dur attribute on p elements.","Timing Test");
addTest("../Timing/BeginEnd003.xml","BeginEnd003","Test the begin and end attributes on p elements in random order. @@Is it a valid test?","Timing Test");
addTest("../Specification/DocumentExample120.xml","DocumentExample120","This test contains the document example from the section 1.2 of the DFXP 1.0 specification, without the layout region.","Specification Test");
addTest("../Specification/DocumentExample822.xml","DocumentExample822","This test contains the document example from the section 8.2.2 of the DFXP 1.0 specification, with the region replacing with a styling.","Specification Test");
addTest("../Specification/DocumentExample823.xml","DocumentExample823","This test contains the document example from the section 8.2.3 of the DFXP 1.0 specification, with the region replacing with a styling.","Specification Test");
addTest("../Specification/DocumentExample824.xml","DocumentExample824","This test contains the document example from the section 8.2.4 of the DFXP 1.0 specification, with the region replacing with a styling.","Specification Test");
addTest("../Specification/DocumentExample825.xml","DocumentExample825","This test contains the document example from the section 8.2.5 of the DFXP 1.0 specification, with the region replacing with a styling.","Specification Test");
