addTest("../Content/Br001.xml","Br001","Test the br element.","Content Test");
addTest("../Content/Paragraph001.xml","Paragraph001","Test the p element with no styling attribute.","Content Test");
addTest("../Content/Paragraph002.xml","Paragraph002","Test the p element with no timing attributes (nothing is displayed).","Content Test");
addTest("../Content/Paragraph003.xml","Paragraph003","Test the p element with styling and timing attributes.","Content Test");
addTest("../Content/Paragraph004.xml","Paragraph004","Test the p element with xml:space default.","Content Test");
addTest("../Content/Paragraph005.xml","Paragraph005","Test the p element with xml:space preserve.","Content Test");
addTest("../Content/Span001.xml","Span001","Test the span element with no attributes.","Content Test");
addTest("../Content/Span002.xml","Span002","Test the span element with a styling attribute.","Content Test");
addTest("../Content/Span003.xml","Span003","Test nested span elements.","Content Test");
addTest("../Content/Span004.xml","Span004","Test nested span elements.","Content Test");
addTest("../Content/Span005.xml","Span005","Test the br element inside a span element.","Content Test");
addTest("../Content/div001.xml","div001","Test nested div elements.","Content Test");
addTest("../Content/div002.xml","div002","Test multiple div elements in the body.","Content Test");
addTest("../Content/div003.xml","div003","Test multiple div elements in the body with the xml:lang attribute.","Content Test");
addTest("../Content/foreign001.xml","foreign001","Test the non-TT namespaces.","Content Test");
addTest("../Content/tt001.xml","tt001","Test the tt element without an xml:space attribute.","Content Test");
addTest("../Content/tt002.xml","tt002","Test the tt element with xml:space preserve.","Content Test");
addTest("../Content/tt003.xml","tt003","Test the tt element with xml:space default.","Content Test");
addTest("../Styling/BackgroundColor001.xml","BackgroundColor001","Test tts:backgroundColor attribute using a named color expression in a div.","Styling Test");
addTest("../Styling/BackgroundColor002.xml","BackgroundColor002","Test tts:backgroundColor attribute using a hash (#rrggbb) color expression in a div.","Styling Test");
addTest("../Styling/BackgroundColor003.xml","BackgroundColor003","Test tts:backgroundColor attribute using a hash (#rrggbbaa) color expression with opacity on the body.","Styling Test");
addTest("../Styling/BackgroundColor004.xml","BackgroundColor004","Test tts:backgroundColor attribute using a rgb() color function on the body.","Styling Test");
addTest("../Styling/BackgroundColor005.xml","BackgroundColor005","Test tts:backgroundColor attribute using a rgba() color function using a span.","Styling Test");
addTest("../Styling/BackgroundColor006.xml","BackgroundColor006","Test tts:backgroundColor attribute using a transparent value.","Styling Test");
addTest("../Styling/BackgroundColor007.xml","BackgroundColor007","Test tts:backgroundColor using a named color expression on the div element.","Styling Test");
addTest("../Styling/BackgroundColor008.xml","BackgroundColor008","Test tts:backgroundColor style using a named color expression in style.","Styling Test");
addTest("../Styling/BackgroundColor009.xml","BackgroundColor009","Test tts:backgroundColor using a named color expression on the body.","Styling Test");
addTest("../Styling/Color001.xml","Color001","Test tts:color attribute using a named color expression.","Styling Test");
addTest("../Styling/Color002.xml","Color002","Test tts:color attribute using a hash (#rrggbb) color expression.","Styling Test");
addTest("../Styling/Color003.xml","Color003","Test tts:color attribute using a hash (#rrggbbaa) color expression with opacity.","Styling Test");
addTest("../Styling/Color004.xml","Color004","Test tts:color attribute using a rgb() color function.","Styling Test");
addTest("../Styling/Color005.xml","Color005","Test tts:color attribute using a rgba() color function.","Styling Test");
addTest("../Styling/Color006.xml","Color006","Test tts:color attribute using a inherit value.","Styling Test");
addTest("../Styling/Color007.xml","Color007","Test tts:color attribute using a transparent value.","Styling Test");
addTest("../Styling/Color008.xml","Color008","Test tts:color attribute with span elements.","Styling Test");
addTest("../Styling/Color009.xml","Color009","Test tts:color style using a named color expression.","Styling Test");
addTest("../Styling/Style001.xml","Style001","Test style attributes in the style element.","Styling Test");
addTest("../Styling/Styling001.xml","Styling001","Test two different styles in the style element.","Styling Test");
addTest("../Styling/TextAlign001.xml","TextAlign001","Test tts:textAlign attribute with the right value in a paragraph.","Styling Test");
addTest("../Styling/TextAlign002.xml","TextAlign002","Test tts:textAlign attribute with the left value in a span.","Styling Test");
addTest("../Styling/TextAlign003.xml","TextAlign003","Test tts:textAlign attribute with the center value in style.","Styling Test");
addTest("../Styling/TextAlign004.xml","TextAlign004","Test tts:textAlign attribute with the right value on the body.","Styling Test");
addTest("../Styling/TextAlign005.xml","TextAlign005","Test tts:textAlign attribute with the left value on div.","Styling Test");
addTest("../Styling/TextAlign006.xml","TextAlign006","Test tts:textAlign attribute with the center value on a span.","Styling Test");
addTest("../Styling/TextDecoration001.xml","TextDecoration001","Test tts:textDecoration attribute using the none value.","Styling Test");
addTest("../Styling/TextDecoration002.xml","TextDecoration002","Test tts:textDecoration attribute using the underline value in a span.","Styling Test");
addTest("../Styling/TextDecoration003.xml","TextDecoration003","Test tts:textDecoration attribute using the none value in a span.","Styling Test");
addTest("../Styling/TextDecoration004.xml","TextDecoration004","Test tts:textDecoration attribute using the underline value in style.","Styling Test");
addTest("../Styling/TextDecoration005.xml","TextDecoration005","Test tts:textDecoration attribute with the underline value in a div.","Styling Test");
addTest("../Styling/TextDecoration006.xml","TextDecoration006","Test tts:textDecoration attribute with the underline value in the body.","Styling Test");
addTest("../Timing/BeginDur001.xml","BeginDur001","Test the begin and dur attributes on p elements.","Timing Test");
addTest("../Timing/BeginEnd001.xml","BeginEnd001","Test the begin and end attributes on p elements.","Timing Test");
addTest("../Timing/BeginEnd002.xml","BeginEnd002","Test the begin attribute with no end or dur attribute on p elements.","Timing Test");
addTest("../Timing/BeginEnd003.xml","BeginEnd003","Test the begin and end attributes on p elements in random order. @@Is it a valid test?","Timing Test");
