name: Build and deploy
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: set target output
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "TARGET_BRANCH=${{ github.event.pull_request.head.ref }}-build" >> $GITHUB_ENV
      - name: set target as gh-pages for main
        if: ${{ github.event_name == 'push' }}
        run: echo "TARGET_BRANCH=gh-pages" >> $GITHUB_ENV
      - name: build with ant
        working-directory: ./spec
        run: ant build
      - name: git push
        working-directory: ./spec/build
        run: |
          cp -a ../../.git ./
          git symbolic-ref HEAD refs/heads/${{ env.TARGET_BRANCH }}
          git fetch origin ${{ env.TARGET_BRANCH }} && git reset origin/${{ env.TARGET_BRANCH }}
          git config user.name "CI (${{ github.actor }})"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "Deploy ${{ env.TARGET_BRANCH }}: ${{ github.sha }}"
          git push --set-upstream origin ${{ env.TARGET_BRANCH }}
      - name: push comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.pull_request.number }},
              body: "Preview: ${{ github.server_url }}/${{ github.repository }}/tree/${{ env.TARGET_BRANCH }}"
            })

